# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menutest',
            name='text',
        ),
    ]
